### ISSUE TITLE
check_initial_file_state:3: = not found

### ISSUE THREAD

**Issue by linonetwo** [simonthum/git-sync#16]
I get

```
git-sync: Preparing. Repo in .git
/xxxrepo/Meme-of-LinOnetwo
git-sync: Mode sync
git-sync: Using origin/master
check_initial_file_state:3: = not found
/xxxrepo/Meme-of-LinOnetwo/scripts/sync.sh:263: = not found
```

when running `/usr/local/bin/zsh /xxxrepo/Meme-of-LinOnetwo/scripts/sync.sh`

**Comment by linonetwo** [comment]
Oh, syntax in zsh and bash is different...

I use `/bin/sh` instead now (MacOS is switching to zsh, but sh will retain).

**Comment by simonthum** [comment]
sh should work, can you confirm please? Would be nice to know ;)

**Comment by linonetwo** [comment]
Yes, it works under `sh`, `sh` is the last safety net.

**Comment by simonthum** [comment]
Thanks a lot!
