### ISSUE TITLE
could not read Username for 'https://github.com': Device not configured

### ISSUE THREAD

**Issue by linonetwo** [simonthum/git-sync#17]
Have you encounter this err before?

```
# TiddlyWiki ErrorsSync failed


From https://github.com/linonetwo/Meme-of-LinOnetwo
 * branch            master     -> FETCH_HEAD
fatal: could not read Username for 'https://github.com': Device not configured
Sync failed
git-sync: Preparing. Repo in .git /Users/linonetwo/Desktop/repo/Meme-of-LinOnetwo
git-sync: Mode sync
git-sync: Using origin/master
git-sync: Fetching from origin/master
git-sync: Pushing changes...
git-sync: git push returned non-zero. Likely a connection failure.

From https://github.com/linonetwo/Meme-of-LinOnetwo
 * branch            master     -> FETCH_HEAD
fatal: could not read Username for 'https://github.com': Device not configured
```

When commit using sudo

<img width="487" alt="Screen Shot 2020-04-20 at 6 55 55 PM" src="https://user-images.githubusercontent.com/3746270/79744230-93d77680-8338-11ea-81ba-e3417d9a7a8e.png">

Sudo because this is a start-up task, monitor by https://github.com/coreybutler/node-mac

**Comment by simonthum** [comment]
Hi, this seems to be a problem with your git setup. Try it manually, and track it down from there.

I do not use OSX personally, but maybe this helps:

https://github.com/kemayo/sublime-text-git/issues/176

**Comment by cjholowatyj** [comment]
Hi @linonetwo, I vaguely recall getting a similar error from git on my server (git-sync needs to be given a username and email address to record as the author of commits git-sync creates). I'm on BitBucket, not GitHub, but I imagine the premise is similar to the following article: [Configure your DVCS username for commits](https://confluence.atlassian.com/bitbucket/configure-your-dvcs-username-for-commits-950301867.html)

**Comment by linonetwo** [comment]
My problem actually comes from the `sudo`, when I run it without administrator privilege, this won't happen again.

Thank you for your solutions! But I find it tricky to config git for administrator account... So I managed to make my script run as normal user.
