### ISSUE TITLE
noUpstream when add bare upstream

### ISSUE THREAD

**Issue by linonetwo** [simonthum/git-sync#24]
[https://github.com/simonthum/git-sync/blob/31cc140df2751e09fae2941054d5b61c34e8b649/git-sync#L178](https://github.com/simonthum/git-sync/blob/31cc140df2751e09fae2941054d5b61c34e8b649/git-sync#L178)

I tried this will return noUpstream when upstream is a bare repo...

**Comment by linonetwo** [comment]
So I rename it to noUpstreamOrBareUpstream in the git-sync-js ...

[https://github.com/tiddly-gittly/git-sync-js/blob/162de1e185e15e171c07b9772bf2a05b0332e4ad/src/inspect.ts#L132-L139](https://github.com/tiddly-gittly/git-sync-js/blob/162de1e185e15e171c07b9772bf2a05b0332e4ad/src/inspect.ts#L132-L139)

I wonder if this will lead to potential bugs?

**Comment by simonthum** [comment]
I just checked; my upstream is indeed bare as I would expect. Maybe you mean a working copy?

**Comment by linonetwo** [comment]
> on the same filesystem with your upstream

Yes, I'm writing tests for my script, so I've created a bare repo as upstream. And I surprisingly found that `git rev-list --count --left-right origin/main...HEAD` returns only stderr ("fatal: blabla same as no upstream")

**Comment by linonetwo** [comment]
Maybe the difference is, I check `git rev-list` when repo when bare repo is just inited, and is just added as remote. At this time, `git rev-list` will not have stdout.

But after a commit + push, it will be `1    1` as normal...

So the problem is at the first time you create a repo in GitHub or GitLab, it may be a bare remote, and `git rev-list` will tell you don't have a remote, the script can still add and commit and push regardless of the `noUpstream`.

**Comment by simonthum** [comment]
I suspect we were talking about different things. A bare repo is one without a working copy; but you probably meant an empty repository containing only the empty tree (4b825dc642cb6eb9a060e54bf8d69288fbee4904).

I wonder if the difference stems from a remote which just got added but was not fetched yet. Could you please double check that?

**Comment by linonetwo** [comment]
If you can read js code, here are the test script [https://github.com/tiddly-gittly/git-sync-js/blob/13bc2a39c46fdcc2b13491fd186981b4105a2edb/test/commitAndSync.test.ts#L16-L26](https://github.com/tiddly-gittly/git-sync-js/blob/13bc2a39c46fdcc2b13491fd186981b4105a2edb/test/commitAndSync.test.ts#L16-L26)

And is [https://github.com/tiddly-gittly/git-sync-js/blob/13bc2a39c46fdcc2b13491fd186981b4105a2edb/test/utils.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L41-L44](https://github.com/tiddly-gittly/git-sync-js/blob/13bc2a39c46fdcc2b13491fd186981b4105a2edb/test/utils.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L41-L44) and [https://github.com/tiddly-gittly/git-sync-js/blob/13bc2a39c46fdcc2b13491fd186981b4105a2edb/src/init.ts#L32-L43](https://github.com/tiddly-gittly/git-sync-js/blob/13bc2a39c46fdcc2b13491fd186981b4105a2edb/src/init.ts#L32-L43)

It basically equal to 

```
cd ./upstreamDir
git init --initial-branch=main --bare
cd ../repo
git remote add origin ../upstreamDir
git rev-list --count --left-right origin/main...HEAD
```

**Comment by simonthum** [comment]
Hi, I guess the difference is in the repo that executes rev-list.

If IIm right the following will work fine:

```
cd ./upstreamDir
git init --initial-branch=main --bare
cd ../repo
git remote add origin ../upstreamDir
git fetch origin    <<<--- This should do the trick
git rev-list --count --left-right origin/main...HEAD
// no error
```
