### ISSUE TITLE
Git-sync-on-inotify crashes when whitepace in GIT_SYNC_DIRECTORY

### ISSUE THREAD

**Issue by RedEtherbloom** [simonthum/git-sync#33]
Hi, I'm trying to setup git-sync/git-sync-on-inotfy, but it keeps crashing when there is a whitspace in the path.

The error log, annonymized, is:
```
fatal: destination path 'Stuff' already exists and is not an empty directory.
<funny NixOS path>-git-sync-on-inotify: line 16: cd: /home/<user>/Stuff Space/Repobasename No such file or directory
fatal: not a git repository (or any of the parent directories): .git
basename: missing operand
Try 'basename --help' for more information.
fatal: not in a git directory
Sync directory: /home/<user>/Stuff Space/Repobasename does not exist and could not be created.
```
The offending line seems to be:
`git clone "$GIT_SYNC_REPOSITORY" "$(basename $GIT_SYNC_DIRECTORY)"`

$GIT_SYNC_DIRECTORY doesn't get escaped with e.g. printf %q, resulting in basename technically getting two strings, split at the whitespace, instead of one.

(Note for debugging: basename in bash has this problem. As I had to learn the hard way during testing, zshs inbuilt basename function escapes the string by default) 

(Additional proposal: GIT_SYNC_REPOSITORY should  probably also get escaped to avoid similar bugs)

**Comment by RedEtherbloom** [comment]
Okay, update, it was actually calling basename in a string that somehow broke on whitespaces. I have no idea why but it should be fixed by #34.

**Comment by simonthum** [comment]
Hi, thanks for your PR. I don't maintain a test setup for sync-on-inotify, but your changes seem safe enough.

**Comment by RedEtherbloom** [comment]
We tested it locally, it seems to work. 
Thanks for your trust.
